---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: server
    driver:
      box: centos65-1.0.6_LearningChef
      network:
        - ["private_network", {ip: "192.168.33.6"}]
      memory: 1536
      synced_folders:
        - ["../../../chef-repo", "/chef-repo"]

suites:
  - name: chef
    run_list:
      - recipe[chef-server::default]
    attributes:
